### ISSUE TITLE
support for multiple winners/teams

### ISSUE THREAD

**Issue by olliestanley** [macalinao/cloudgame#1]
affects https://github.com/simplyianm/cloudgame/blob/master/src/main/java/com/simplyian/cloudgame/events/GameEndEvent.java

add support for having a game won by a team of players

**Comment by macalinao** [comment]
I propose a `Winner<T extends State>` class. So a FFA winner would return a `FFAWinner extends Winner<FFAState>`. What do you think?

**Comment by olliestanley** [comment]
Seems a valid proposal. That would allow for more flexibility than just a List<Player> or something.

**Comment by olliestanley** [comment]
OK - I wrote some code for this and put it in a new branch

https://github.com/simplyianm/cloudgame/tree/winners

Tell me what you think
