### ISSUE TITLE
Game Master system

### ISSUE THREAD

**Issue by macalinao** [macalinao/cloudgame#11]
Games should have the option to follow an automated lobby system, host system, or whatever they want.

**Comment by macalinao** [comment]
This is next on my todo list, decoupling the actual game from the game creation/setup

**Comment by macalinao** [comment]
So there will be a Game Master interface, referring to the entity that started the game.

**Comment by olliestanley** [comment]
dam it ian i don't need this pressure on me

**Comment by olliestanley** [comment]
i guess this is done too?

**Comment by macalinao** [comment]
yeah pretty much done
