### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by macalinao** [macalinao/cloudgame#25]
How about a way to mix and match listeners really easily? Something like this:

``` java
// in Gameplay#onEnable()
mixin(NoPvp.class);
```

would add the NoPvp listener (a one method class) to the project. NoPvp would extend GameListener and would take a Gameplay in its constructor. This should be really simple for people to use.

This is an alternative to `setAllowPvp(false)` which could make our Gameplay class really long and hard to maintain.

**Comment by macalinao** [comment]
Let's add more to this idea. `State` is a really ugly class. You have to extend it, and it's generally kind of hard to access. How about giving Mixins their own states? Like `gameplay.state(MixinState.class);` would return the state that Mixin registered. Mixins should also have a setup method where they register their States.

**Comment by macalinao** [comment]
So basically, instead of dealing with inheritance of games that will very likely share similar features, you'll have a sort of multiple inheritance system that lets you mix and match features from games. For example, an FFA and a Team game may both want to use guns.

**Comment by olliestanley** [comment]
sounds good

**Comment by olliestanley** [comment]
Mixin idea: RollbackAfter.class

After the end of a game, the arena is rolled back to the state it was in before the game.

**Comment by macalinao** [comment]
Sure. I guess you would add listeners for GameStart and GameEnd to do that

**Comment by macalinao** [comment]
or track changes (probably easier)

**Comment by macalinao** [comment]
we need to remove generics from games in order to make mixins work as intended. State should be refactored out and replaced with a Participants object.

**Comment by macalinao** [comment]
Ok i'm just going to name `MixinState` `State` because we are getting rid of the original `State`

**Comment by olliestanley** [comment]
is this done?

**Comment by macalinao** [comment]
yes
