### ISSUE TITLE
move things out of the hostedffa listeners

### ISSUE THREAD

**Issue by olliestanley** [macalinao/cloudgame#26]
gameplay implementations shouldn't have to deal with stuff like this:

https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGameListener.java#L83
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGameListener.java#L95
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGameListener.java#L102
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGameListener.java#L113-115

and more

**Comment by macalinao** [comment]
Good point. Most games should have a concept of game "flow" built in. We can put this in some kind of mixin (#25)

**Comment by olliestanley** [comment]
i feel like there are still a couple of things which can be moved out of the listeners

https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGameListener.java#L38-42
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGamePlayerListener.java#L51-68
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGamePlayerListener.java#L84-93
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGamePlayerListener.java#L119-124
https://github.com/simplyianm/cloudgame/blob/master/src/main/java/pw/ian/cloudgame/gameplay/hostedffa/listeners/FFAGamePlayerListener.java#L140

**Comment by macalinao** [comment]
Yeah, i agree with that. If you want to do it go ahead. I really just want to get rid of HostedFFA completely.

**Comment by olliestanley** [comment]
i think this is pretty much resolved now

**Comment by macalinao** [comment]
yes
