### ISSUE TITLE
Publish to Sonatype OSS

### ISSUE THREAD

**Issue by macalinao** [macalinao/cloudgame#6]
Sonatype OSS is a Maven Repository host. Publishing there would let us write game modes in external plugins. I already have a repo on there; I just need to add the Gradle stuff. It'd be nice if someone researches what I need to add to the `build.gradle`... @DziNeIT

**Comment by olliestanley** [comment]
I don't know gradle or anything :P

**Comment by macalinao** [comment]
Then learn it :smiley:  It's awesome

**Comment by olliestanley** [comment]
I read your non-edited message lolz future

**Comment by macalinao** [comment]
https://support.sonatype.com/entries/21580432-how-do-i-configure-my-gradle-build-to-publish-artifacts-to-nexus

**Comment by macalinao** [comment]
seems simple, though we're going to need to use a real version number system i guess

**Comment by olliestanley** [comment]
yey real versions!
