### ISSUE TITLE
Put HostedFFA in its own plugin

### ISSUE THREAD

**Issue by macalinao** [macalinao/cloudgame#7]
Releasing HostedFFA will make OG look really cookie-cutter. It should be in the MattMG plugin (which is not on Github atm). Needs to be done after #5 and #6.

**Comment by macalinao** [comment]
#5 and #6 are completed. This is now a high-ish priority.

**Comment by olliestanley** [comment]
so you open sourced it with HostedFFA still in it. you genius :P

**Comment by macalinao** [comment]
Yolo

**Comment by olliestanley** [comment]
i guess this is now scrapped as it's a mixin?

**Comment by macalinao** [comment]
yes
